// ═══════════════════════════════════════════════════
//  VOLTMATCH — Base de données de batteries (11 entrées)
// ═══════════════════════════════════════════════════

const BATTERIES = [
  // ── Renault EZ1 Seconde vie ──────────────────────
  {
    id: 'renault-ez1-10kwh',
    manufacturer: 'Renault',
    model: 'EZ1 Second Life 10 kWh',
    type: 'seconde vie',
    energyKwh: 10,
    voltage: 48,
    capacityAh: 208,
    chemistry: 'LFP',
    maxPowerW: 5000,
    weightKg: 91,
    dimensionsMm: { l: 600, w: 480, h: 200 },
    cycles: 2500,
    warrantyYears: 1,
    price: 900,
    currency: 'EUR',
    stock: 24,
    purchaseUrl: '#',
    dataReliability: 'estimated',
    dataNote: 'Valeurs estimées (LFP 110 Wh/kg, seconde vie) — garantie 1 an adaptée à l\'usage seconde vie.'
  },
  // ── BYD ───────────────────────────────────────────
  {
    id: 'byd-hvs-5',
    manufacturer: 'BYD',
    model: 'Battery-Box Premium HVS 5.1',
    type: 'neuf',
    energyKwh: 5.12,
    voltage: 204,
    capacityAh: 25,
    chemistry: 'LFP',
    maxPowerW: 5120,
    weightKg: 91,
    dimensionsMm: { l: 584, w: 219, h: 998 },
    cycles: 6000,
    warrantyYears: 10,
    price: 2295,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bydbatterybox.com',
    dataReliability: 'verified',
    dataNote: 'Poids 91kg et prix 2295€ confirmés sur page revendeur (BYD HVS 5.1 / 1 module). Ces valeurs servent aussi d\'ancres pour l\'interpolation de la config 10.2 kWh (4 modules).'
  },
  {
    id: 'byd-hvs-7.7',
    manufacturer: 'BYD',
    model: 'Battery-Box Premium HVS 7.7',
    type: 'commercial',
    energyKwh: 7.68,
    voltage: 307,
    capacityAh: 25,
    chemistry: 'LFP',
    weightKg: 129,
    cycles: 6000,
    warrantyYears: 10,
    price: 3194,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bydbatterybox.com',
    dataReliability: 'verified',
    dataNote: 'Specs et prix confirmés sur fiche produit officielle du revendeur (3 modules HVS, 945x585x298mm).'
  },
  {
    id: 'byd-hvs-10.2',
    manufacturer: 'BYD',
    model: 'Battery-Box Premium HVS 10.2',
    type: 'neuf',
    energyKwh: 10.24,
    voltage: 409.6,
    capacityAh: 25,
    chemistry: 'LFP',
    maxPowerW: 10240,
    weightKg: 167,
    dimensionsMm: { l: 584, w: 219, h: 998 },
    cycles: 6000,
    warrantyYears: 10,
    price: 4092,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bydbatterybox.com',
    dataReliability: 'estimated',
    dataNote: 'Poids et prix extrapolés par interpolation entre HVS 5.1 (91kg/2295€, confirmés) et HVS 12.8 (205kg/4990€, confirmés) — pas de fiche directe pour cette config à 4 modules.'
  },
  {
    id: 'byd-hvs-12.8',
    manufacturer: 'BYD',
    model: 'Battery-Box Premium HVS 12.8',
    type: 'commercial',
    energyKwh: 12.8,
    voltage: 512,
    capacityAh: 25,
    chemistry: 'LFP',
    weightKg: 205,
    cycles: 6000,
    warrantyYears: 10,
    price: 4990,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bydbatterybox.com',
    dataReliability: 'verified',
    dataNote: 'Specs et prix confirmés sur fiche produit officielle du revendeur (5 modules HVS, 1411x585x298mm).'
  },
  // ── LG Energy Solution ────────────────────────────
  {
    id: 'lg-resu10h-prime',
    manufacturer: 'LG Energy Solution',
    model: 'RESU10H Prime',
    type: 'neuf',
    energyKwh: 9.6,
    voltage: 400,
    capacityAh: 24,
    chemistry: 'NMC',
    maxPowerW: 5000,
    weightKg: 111,
    dimensionsMm: { l: 504, w: 295, h: 817 },
    cycles: 6000,
    warrantyYears: 10,
    price: 6497,
    currency: 'EUR',
    stock: 200,
    purchaseUrl: '#',
    dataReliability: 'estimated',
    dataNote: 'CONFIRMÉS (fiche produit LG) : énergie 9.6 kWh, poids 111 kg, IP55, chimie NMC, garantie 10 ans. NON CONFIRMÉS (estimation) : tension nominale 400V (gamme HV typique de ce format, non vérifiée sur facture) et prix 6497€ (fourchette observée sur revendeurs tiers, non officiel LG).'
  },
  {
    id: 'lg-resu16h-prime',
    manufacturer: 'LG Energy Solution',
    model: 'RESU16H Prime',
    type: 'commercial',
    energyKwh: 16,
    voltage: 400,
    capacityAh: 40,
    chemistry: 'NMC',
    weightKg: 159,
    cycles: 6000,
    warrantyYears: 10,
    price: 8987,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.lgessbattery.com',
    dataReliability: 'estimated',
    dataNote: 'Énergie (16kWh), poids (159kg) et IP55 confirmés sur fiche officielle LG. Tension et prix estimés par recherche complémentaire.'
  },
  {
    id: 'lg-resu12',
    manufacturer: 'LG Energy Solution',
    model: 'RESU12',
    type: 'commercial',
    energyKwh: 11.7,
    voltage: 51.8,
    capacityAh: 226,
    chemistry: 'NMC',
    weightKg: 98.5,
    cycles: 6000,
    warrantyYears: 10,
    price: 5878,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.lgessbattery.com',
    dataReliability: 'estimated',
    dataNote: 'Énergie utile (11.7kWh), poids (98.5kg) confirmés sur fiche officielle LG, décrite comme faisant partie de la "gamme basse tension" LG RESU — tension 51.8V. Prix estimé.'
  },
  // ── Pylontech ─────────────────────────────────────
  {
    id: 'pylontech-us5000',
    manufacturer: 'Pylontech',
    model: 'US5000',
    type: 'neuf',
    energyKwh: 4.56,
    voltage: 48,
    capacityAh: 100,
    dod: 95,
    designLifeYears: 15,
    chemistry: 'LFP',
    maxPowerW: 5000,
    weightKg: 39.7,
    dimensionsMm: { l: 442, w: 220, h: 161 },
    cycles: 6000,
    warrantyYears: 15,
    price: 3300,
    currency: 'USD',
    stock: 999,
    purchaseUrl: '#',
    dataReliability: 'estimated',
    dataNote: 'Specs techniques confirmées sur fiche officielle Pylontech (datasheet PDF) avec certifs UL/IEC/UN38.3. Prix non communiqué sur cette source, estimation d\'un revendeur tiers.'
  },
  {
    id: 'pylontech-h48074',
    manufacturer: 'Pylontech',
    model: 'H48074 (74Ah)',
    type: 'neuf',
    energyKwh: 3.552,
    voltage: 48,
    capacityAh: 74,
    chemistry: 'LFP',
    maxPowerW: 3552,
    weightKg: 32,
    dimensionsMm: { l: 422, w: 390, h: 132 },
    cycles: 5000,
    warrantyYears: 15,
    price: 1650,
    currency: 'USD',
    stock: 999,
    purchaseUrl: '#',
    dataReliability: 'verified',
    dataNote: 'Fiche constructeur Pylontech. Entrée de gamme rack (les prix varient selon la région).'
  },
  // ── Tesla Powerwall ───────────────────────────────
  {
    id: 'tesla-powerwall-3',
    manufacturer: 'Tesla',
    model: 'Powerwall 3',
    type: 'neuf',
    energyKwh: 13.5,
    voltage: 50,
    capacityAh: 270,
    chemistry: 'LFP',
    maxPowerW: 11500,
    weightKg: 124,
    dimensionsMm: { l: 1105, w: 609, h: 193 },
    cycles: 4000,
    warrantyYears: 10,
    price: 11959,
    currency: 'USD',
    stock: 999,
    purchaseUrl: 'https://www.tesla.com/powerwall',
    dataReliability: 'verified',
    dataNote: 'Données Tesla officielles. Prix hors installation.'
  },
  // ── Dyness ────────────────────────────────────────
  {
    id: 'dyness-tower-t7',
    manufacturer: 'Dyness',
    model: 'Tower T7',
    type: 'commercial',
    energyKwh: 7.10,
    voltage: 192,
    capacityAh: 37,
    chemistry: 'LFP',
    weightKg: 105,
    cycles: 6000,
    warrantyYears: 10,
    price: 1332,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.dyness.com',
    dataReliability: 'estimated',
    dataNote: 'Specs confirmées sur datasheet officiel Dyness (DOD 95%, IP54). Prix estimé par extrapolation €/kWh depuis le Tower T10 (prix confirmé multi-revendeurs).'
  },
  {
    id: 'dyness-tower-t10',
    manufacturer: 'Dyness',
    model: 'Tower T10',
    type: 'neuf',
    energyKwh: 10.66,
    voltage: 288,
    capacityAh: 37,
    chemistry: 'LFP',
    maxPowerW: 10660,
    weightKg: 146,
    dimensionsMm: { l: 622, w: 362, h: 1330 },
    cycles: 6000,
    warrantyYears: 10,
    price: 2000,
    currency: 'EUR',
    stock: 150,
    purchaseUrl: '#',
    dataReliability: 'verified',
    dataNote: 'Fiche constructeur Dyness vérifiée (DOD 95%, IP54). Prix moyen EU.'
  },
  {
    id: 'dyness-tower-t14',
    manufacturer: 'Dyness',
    model: 'Tower T14',
    type: 'commercial',
    energyKwh: 14.21,
    voltage: 384,
    capacityAh: 37,
    chemistry: 'LFP',
    weightKg: 187,
    cycles: 6000,
    warrantyYears: 10,
    price: 2666,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.dyness.com',
    dataReliability: 'estimated',
    dataNote: 'Specs confirmées sur datasheet officiel Dyness (DOD 95%, IP54). Prix estimé par extrapolation €/kWh depuis le Tower T10.'
  },
  {
    id: 'dyness-tower-t17',
    manufacturer: 'Dyness',
    model: 'Tower T17',
    type: 'commercial',
    energyKwh: 17.76,
    voltage: 480,
    capacityAh: 37,
    chemistry: 'LFP',
    weightKg: 228,
    cycles: 6000,
    warrantyYears: 10,
    price: 3332,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.dyness.com',
    dataReliability: 'estimated',
    dataNote: 'Specs confirmées sur datasheet officiel Dyness (DOD 95%, IP54). Prix estimé par extrapolation €/kWh depuis le Tower T10.'
  },
  {
    id: 'dyness-tower-t21',
    manufacturer: 'Dyness',
    model: 'Tower T21',
    type: 'commercial',
    energyKwh: 21.31,
    voltage: 576,
    capacityAh: 37,
    chemistry: 'LFP',
    weightKg: 269,
    cycles: 6000,
    warrantyYears: 10,
    price: 3998,
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.dyness.com',
    dataReliability: 'estimated',
    dataNote: 'Specs confirmées sur datasheet officiel Dyness (DOD 95%, IP54). Prix estimé par extrapolation €/kWh depuis le Tower T10.'
  },
  // ── EcoFlow ───────────────────────────────────────
  {
    id: 'ecoflow-delta-pro',
    manufacturer: 'EcoFlow',
    model: 'DELTA Pro 3.6 kWh',
    type: 'neuf',
    energyKwh: 3.6,
    voltage: 48,
    capacityAh: 75,
    chemistry: 'LFP',
    maxPowerW: 3600,
    weightKg: 45,
    dimensionsMm: { l: 635, w: 284, h: 420 },
    cycles: 3500,
    warrantyYears: 5,
    price: 1599,
    currency: 'USD',
    stock: 999,
    purchaseUrl: 'https://www.ecoflow.com',
    dataReliability: 'verified',
    dataNote: 'Prix et specs officiels EcoFlow (les prix de vente au détail varient selon le revendeur et la région).'
  },
  {
    id: 'ecoflow-delta-pro-extra',
    manufacturer: 'EcoFlow',
    model: 'DELTA Pro + Smart Extra Battery',
    type: 'commercial',
    energyKwh: 7.2,
    voltage: 48,
    capacityAh: 150,
    chemistry: 'LFP',
    weightKg: 83,
    cycles: 3500,
    warrantyYears: 5,
    price: 2709,
    currency: 'USD',
    stock: 999,
    purchaseUrl: 'https://www.ecoflow.com',
    dataReliability: 'verified',
    dataNote: 'Prix officiel confirmé (bundle EcoFlow US). Poids estimé en doublant le poids unitaire du DELTA Pro de base (déjà confirmé officiellement).'
  },
  {
    id: 'ecoflow-delta-pro-ultra',
    manufacturer: 'EcoFlow',
    model: 'DELTA Pro Ultra 6 kWh',
    type: 'neuf',
    energyKwh: 6, // confirmé
    voltage: 48, // NON confirmé — supposition par cohérence avec la gamme DELTA Pro
    capacityAh: 125, // NON confirmé, calculé depuis la tension supposée
    chemistry: 'LFP',
    maxPowerW: 7200, // confirmé
    weightKg: 82, // estimé par analogie avec le DELTA Pro Ultra X (onduleur 31.7kg + batterie 50.7kg)
    dimensionsMm: { l: 700, w: 320, h: 500 }, // NON confirmé
    cycles: 3500, // corrigé — 3500 confirmé officiellement, pas 4000
    warrantyYears: 5, // NON confirmé pour ce modèle précis
    price: 5499, // NON confirmé — EcoFlow ne publie pas de prix fixe pour ce produit
    currency: 'USD',
    stock: 300,
    purchaseUrl: 'https://www.ecoflow.com/us/delta-pro-ultra',
    dataReliability: 'estimated',
    dataNote: 'Capacité (6kWh), puissance (7200W) et cycles (3500 à 80% SOH) confirmés sur fiche officielle EcoFlow. Tension, capacité Ah, poids (estimé par analogie avec un produit proche), dimensions, garantie et prix ne sont PAS publiés officiellement pour ce modèle — EcoFlow oriente vers un devis personnalisé.'
  },

  // ── Bluetti ───────────────────────────────────────
  {
    id: 'bluetti-ep760-1b500',
    manufacturer: 'Bluetti',
    model: 'EP760 + 1×B500 Home Battery Backup',
    type: 'commercial',
    energyKwh: 4.96,
    voltage: 99.2, // confirmé fiche technique B500
    capacityAh: 50, // 4960 / 99.2
    chemistry: 'LFP',
    weightKg: 104, // 46 (EP760) + 58 (B500)
    cycles: 3500, // estimé, cohérent avec fiches B500/EP600 comparables
    warrantyYears: 10,
    price: 5500, // estimé — converti/extrapolé du prix de lancement AU (~9999 AUD pour 2×B500), pas un prix EUR officiel
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bluettipower.eu',
    dataReliability: 'estimated',
    dataNote: 'Énergie, poids, garantie, dimensions et tension confirmés sur fiches techniques officielles Bluetti. Cycles et prix estimés (prix converti/extrapolé depuis les tarifs de lancement australiens, non un prix officiel du marché EU).'
  },
  {
    id: 'bluetti-ep760-2b500',
    manufacturer: 'Bluetti',
    model: 'EP760 + 2×B500 Home Battery Backup',
    type: 'commercial',
    energyKwh: 9.9,
    voltage: 99.2,
    capacityAh: 100, // 9900 / 99.2
    chemistry: 'LFP',
    weightKg: 162,
    cycles: 3500,
    warrantyYears: 10,
    price: 6500, // estimé depuis prix de lancement AU (9999 AUD converti)
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bluettipower.eu',
    dataReliability: 'estimated',
    dataNote: 'Énergie, poids, garantie, dimensions et tension confirmés sur fiches officielles. Prix estimé par conversion du tarif de lancement australien (9999 AUD) — à confirmer sur le marché EU au moment de l\'achat.'
  },
  {
    id: 'bluetti-ep760-3b500',
    manufacturer: 'Bluetti',
    model: 'EP760 + 3×B500 Home Battery Backup',
    type: 'commercial',
    energyKwh: 14.8,
    voltage: 99.2,
    capacityAh: 149, // 14800 / 99.2
    chemistry: 'LFP',
    weightKg: 220,
    cycles: 3500,
    warrantyYears: 10,
    price: 9800, // estimé depuis prix de lancement AU (14998 AUD converti)
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bluettipower.eu',
    dataReliability: 'estimated',
    dataNote: 'Énergie, poids, garantie, dimensions et tension confirmés sur fiches officielles. Prix estimé par conversion du tarif de lancement australien (14998 AUD).'
  },
  {
    id: 'bluetti-ep760-4b500',
    manufacturer: 'Bluetti',
    model: 'EP760 + 4×B500 Home Battery Backup',
    type: 'commercial',
    energyKwh: 19.8,
    voltage: 99.2,
    capacityAh: 200, // 19800 / 99.2
    chemistry: 'LFP',
    weightKg: 278,
    cycles: 3500,
    warrantyYears: 10,
    price: 13000, // estimé depuis prix de lancement AU (19999 AUD converti)
    currency: 'EUR',
    stock: 999,
    purchaseUrl: 'https://www.bluettipower.eu',
    dataReliability: 'estimated',
    dataNote: 'Énergie, poids, garantie, dimensions et tension confirmés sur fiches officielles. Prix estimé par conversion du tarif de lancement australien (19999 AUD) — non un prix officiel EUR.'
  }
];